# Generated by Django 3.2.6 on 2021-09-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='phone',
            field=models.CharField(default=1234567, max_length=30, unique=True, verbose_name='phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newuser',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
