# Generated by Django 3.2.6 on 2021-08-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_auto_20210830_0619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Factory_line',
            new_name='Production_line',
        ),
        migrations.RenameModel(
            old_name='Factory_salon',
            new_name='Shop_floor',
        ),
    ]
