# Generated by Django 3.2.6 on 2021-09-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_type',
            name='icon',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
