# Generated by Django 3.2.6 on 2021-09-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_alter_sensor_type_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_line',
            old_name='belongs_to',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='shop_floor',
            old_name='belongs_to',
            new_name='owner',
        ),
    ]
