# Generated by Django 3.2.6 on 2021-09-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_auto_20210902_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factory',
            old_name='owners',
            new_name='owner',
        ),
    ]
