# Generated by Django 3.2.6 on 2021-09-02 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_rename_owners_factory_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mac_addr', models.CharField(max_length=100)),
                ('pin_addr', models.CharField(max_length=100)),
                ('place_inline', models.IntegerField()),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.sensor_type')),
            ],
        ),
    ]
