# Generated by Django 3.2.6 on 2021-09-04 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0011_auto_20210902_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='factory.productline'),
            preserve_default=False,
        ),
    ]
