# Generated by Django 3.2.6 on 2021-09-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0012_sensor_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensortype',
            old_name='icon',
            new_name='img',
        ),
    ]
