# Generated by Django 3.2.6 on 2021-09-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0013_rename_icon_sensortype_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensortype',
            old_name='img',
            new_name='icon',
        ),
    ]
