# Generated by Django 3.2.6 on 2021-09-09 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factory', '0014_rename_img_sensortype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='owner',
            field=models.ManyToManyField(related_name='factories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='icon',
            field=models.ImageField(default='default.jpg', upload_to='sensor_pics'),
        ),
    ]
