# Generated by Django 3.2.6 on 2021-09-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0015_auto_20210909_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='pin_addr',
            new_name='port',
        ),
    ]
