# Generated by Django 3.2.6 on 2021-09-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0016_rename_pin_addr_sensor_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='live_data',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
