# Generated by Django 3.2.6 on 2021-09-13 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0017_sensor_live_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
