# Generated by Django 3.2.6 on 2021-10-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0022_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productline',
            old_name='owner',
            new_name='floor_id',
        ),
        migrations.RenameField(
            model_name='productsubline',
            old_name='owner',
            new_name='line_id',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='owner',
            new_name='subline_id',
        ),
        migrations.RenameField(
            model_name='shopfloor',
            old_name='owner',
            new_name='factory_id',
        ),
    ]
