# Generated by Django 3.2.6 on 2021-10-17 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0023_auto_20211017_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='factory_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='factory.factory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='line_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='factory.productline'),
            preserve_default=False,
        ),
    ]
