# Generated by Django 3.2.6 on 2021-10-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0026_alter_shift_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='factory_id',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='line_id',
        ),
    ]
