# Generated by Django 3.2.6 on 2021-11-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0029_alter_sensor_line_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='factory_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='factory.factory'),
            preserve_default=False,
        ),
    ]
